package com.example.myapplication

class CategoryItemManager {
    companion object{
        fun getItem(): List<CategoryItem> = listOf(
            CategoryItem(
                0,
                R.drawable.icon_dog,
                "강아지"
            ),
            CategoryItem(
                1,
                R.drawable.icon_cat,
                "고양이"
            ),
            CategoryItem(
                2,
                R.drawable.icon_parrot,
                "앵무새"
            ),
            CategoryItem(
                3,
                R.drawable.icon_elephant,
                "코끼리"
            ),
            CategoryItem(
                4,
                R.drawable.icon_giraffe,
                "기린"
            ),
            CategoryItem(
                5,
                R.drawable.icon_panda,
                "판다"
            ),
            CategoryItem(
                6,
                R.drawable.icon_crocodile,
                "악어"
            ),
            CategoryItem(
                7,
                R.drawable.icon_hamster,
                "햄스터"
            ),
            CategoryItem(
                8,
                R.drawable.icon_kangaroo,
                "캥거루"
            ),
            CategoryItem(
                9,
                R.drawable.icon_camel,
                "낙타"
            ),
            CategoryItem(
                10,
                R.drawable.icon_sheep,
                "양"
            ),
            CategoryItem(
                11,
                R.drawable.icon_whale,
                "고래"
            ),
            CategoryItem(
                12,
                R.drawable.icon_wolf,
                "늑대"
            ),
            CategoryItem(
                13,
                R.drawable.icon_monkey,
                "원숭이"
            ),
            CategoryItem(
                14,
                R.drawable.icon_bear,
                "곰"
            ),
            CategoryItem(
                15,
                R.drawable.icon_rabbit,
                "토끼"
            ),
            CategoryItem(
                16,
                R.drawable.icon_penguin,
                "펭귄"
            )
        )
        fun getPlus(): List<CategoryItem> = listOf(
            CategoryItem(
                1,
                R.drawable.icon_plus,
                "추가"
            )
        )
    }
}